name: .NET

on:
  push:
    branches: [ "master" ]  
  pull_request:
    branches: [ "master" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Newwebapiproject.sln

      - name: Build
        run: dotnet build Newwebapiproject.sln --no-restore

      - name: Run Unit Tests
        run: dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Check Unit Test Status
        run: |
          if [ $? -ne 0 ]; then
            echo "Unit tests failed. Preventing merge."
            exit 1
          fi
