# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Newwebapiproject.sln
    - name: Build
      run: dotnet build Newwebapiproject.sln --no-restore
    - name: Test
           test_exit_code=0
           dotnet build
      run: dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
           test_exit_code=$?
           if [ $test_exit_code -ne 0 ]; then
            echo "Unit tests failed. Preventing merge."
            exit 1
           fi
